# Site settings
title: wcy123 
email: wcy123@gmail.com
description: "my blog"
baseurl: ""
github_username:  wcy123
comments: true
# Build settings
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
   coderay_line_numbers: nil
permalink: pretty
