[book]
authors = ["WangChunye"]
language = "cn"
multilingual = true
src = "src"
title = "Wang Chunye"


[output.html]
mathjax-support = true
google-analytics = "UA-98267158-1"

[output.html.playpen]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2